version: '3.3'

services:
  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"